// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIim6rDYFDh34rp9MKycOWKMFOYouomJI',
    appId: '1:339968175264:web:24018c329edcd5bbabedc5',
    messagingSenderId: '339968175264',
    projectId: 'askforrent-45ba8',
    authDomain: 'askforrent-45ba8.firebaseapp.com',
    storageBucket: 'askforrent-45ba8.appspot.com',
    measurementId: 'G-W74TVQFH1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwdv9PMH7IBEm4x6vjlNaPc066apAr7xM',
    appId: '1:339968175264:android:6f06523014202071abedc5',
    messagingSenderId: '339968175264',
    projectId: 'askforrent-45ba8',
    storageBucket: 'askforrent-45ba8.appspot.com',
  );
}
